/* Items of config-dialog */

#define CFG_DIALOG                  1800

#define CFG_BUT_SAVE                1805
#define CFG_BUT_CANCEL              1806
#define CFG_NOTEBOOK                1807

#define CFG_NB_PAGE1                1900
#define CFG_NB_PAGE2                1901
#define CFG_NB_PAGE3                1902
#define CFG_NB_PAGE4                1903

#define CFG_NBP1_DELAY              2000
#define CFG_NBP1_44KHZ              2001
#define CFG_NBP1_DELPROMPT          2002
#define CFG_NBP1_MAXRECTIME         2003
#define CFG_NBP1_LOGFILE            2005
#define CFG_NBP1_IGNOREEMPTY        2006
#define CFG_NBP1_SHOWDIGITAL        2007
#define CFG_NBP1_FLASH              2008
#define CFG_NBP1_EXPAND             2009
#define CFG_NBP1_DTMF               2010
#define CFG_NBP1_SILENCE            2011
#define CFG_NBP1_POPUPWINDOW        2012
#define CFG_NBP1_RINGING            2013
#define CFG_NBP1_RINGING_FILE       2014
#define CFG_NBP1_RINGING_FDLG       2015
#define CFG_NBP1_WELCOME_FILE       2016
#define CFG_NBP1_WELCOME_FDLG       2017
#define CFG_NBP1_ULAW_CODEC         2018
#define CFG_NBP1_NOTIFY_NUMBER      2019

#define CFG_NBP2_CNTR               2030
#define CFG_NBP3_CNTR               2031
#define CFG_NBP4_CNTR               2032

#define CFG_PEOPLE_POPUP            3000
#define CFG_PEOPLE_ADD              3001
#define CFG_PEOPLE_DEL              3002
#define CFG_PEOPLE_QDEL             3003
#define CFG_PEOPLE_EDIT             3004
#define CFG_PEOPLE_QEDIT            3005

#define CFG_PEOPLE_EDITDLG          3010
#define CFG_PEOPLE_EDITDLG_OK       3011
#define CFG_PEOPLE_EDITDLG_CANCEL   3012
#define CFG_PEOPLE_EDITDLG_NUMBER   3013
#define CFG_PEOPLE_EDITDLG_NAME     3014
#define CFG_PEOPLE_EDITDLG_FILE     3015
#define CFG_PEOPLE_EDITDLG_FILEDLG  3016
#define CFG_PEOPLE_EDITDLG_MAXRECTIM 3017
#define CFG_PEOPLE_EDITDLG_DELAY    3018
#define CFG_PEOPLE_EDITDLG_REJECT   3019
#define CFG_PEOPLE_EDITDLG_ACTIVE   3020
#define CFG_PEOPLE_EDITDLG_RINGING  3021
#define CFG_PEOPLE_EDITDLG_RINGING_FDLG 3022
#define CFG_PEOPLE_EDITDLG_NOTIFY   3023

#define CFG_PORTS_POPUP             3200
#define CFG_PORTS_EDIT              3201
#define CFG_PORTS_QEDIT             3202
#define CFG_PORTS_ADD               3203
#define CFG_PORTS_DEL               3204
#define CFG_PORTS_QDEL              3205

#define CFG_PORTS_EDITDLG           3210
#define CFG_PORTS_EDITDLG_OK        3211
#define CFG_PORTS_EDITDLG_CANCEL    3212
#define CFG_PORTS_EDITDLG_DESCR     3213
#define CFG_PORTS_EDITDLG_FILE      3214
#define CFG_PORTS_EDITDLG_FILEDLG   3215
#define CFG_PORTS_EDITDLG_MAXRECTIM 3216
#define CFG_PORTS_EDITDLG_DELAY     3217
#define CFG_PORTS_EDITDLG_REJECT    3218
#define CFG_PORTS_EDITDLG_NUMBER    3219
#define CFG_PORTS_EDITDLG_ACTIVE    3220
#define CFG_PORTS_EDITDLG_RINGING   3221
#define CFG_PORTS_EDITDLG_RINGING_FDLG 3222
#define CFG_PORTS_EDITDLG_NOTIFY    3223

#define CFG_DTMF_POPUP              3300
#define CFG_DTMF_EDIT               3301
#define CFG_DTMF_QEDIT              3302
#define CFG_DTMF_ADD                3303
#define CFG_DTMF_DEL                3304
#define CFG_DTMF_QDEL               3305

#define CFG_DTMF_EDITDLG            3310
#define CFG_DTMF_EDITDLG_OK         3311
#define CFG_DTMF_EDITDLG_CANCEL     3312
#define CFG_DTMF_EDITDLG_ACTIVE     3313
#define CFG_DTMF_EDITDLG_CODE       3314

#define CFG_DTMF_EDITDLG_RB_RCONTROL  3315
#define CFG_DTMF_EDITDLG_RB_SETNOTIFY 3316
#define CFG_DTMF_EDITDLG_RB_REBOOT    3317
#define CFG_DTMF_EDITDLG_RB_DEACT     3318
#define CFG_DTMF_EDITDLG_RB_QUIT      3319
#define CFG_DTMF_EDITDLG_RB_EXEC      3320

#define CFG_DTMF_EDITDLG_EXEC_PRG   3321
#define CFG_DTMF_EDITDLG_EXEC_ARG   3322
#define CFG_DTMF_EDITDLG_EXEC_TITLE 3323

